/*PG-PINT*/

DROP TABLE IF EXISTS RESULTADOS;
DROP TABLE IF EXISTS SINCRONO;
DROP TABLE IF EXISTS OCORRENCIAS_EDICOES;
DROP TABLE IF EXISTS NOTIFICACOES_CURSO;
DROP TABLE IF EXISTS INSCRICOES;
DROP TABLE IF EXISTS FORMANDOS;
DROP TABLE IF EXISTS FORMADORES;
DROP TABLE IF EXISTS DENUNCIA;
DROP TABLE IF EXISTS TIPO_DENUNCIA;
DROP TABLE IF EXISTS CONTEUDOS;
DROP TABLE IF EXISTS TIPO_FORMATO;
DROP TABLE IF EXISTS COMENTARIO;
DROP TABLE IF EXISTS AVALIACOES;
DROP TABLE IF EXISTS NOTIFICACOES_POST;
DROP TABLE IF EXISTS POST;
DROP TABLE IF EXISTS CONTEUDOS_PARTILHADO;
DROP TABLE IF EXISTS AULAS;
DROP TABLE IF EXISTS ASSINCRONO;
DROP TABLE IF EXISTS "2FA";
DROP TABLE IF EXISTS S_S_O;
DROP TABLE IF EXISTS CURSOS;
DROP TABLE IF EXISTS GESTOR_ADMINISTRADOR;
DROP TABLE IF EXISTS UTILIZADOR;
DROP TABLE IF EXISTS TOPICO;
DROP TABLE IF EXISTS AREA;
DROP TABLE IF EXISTS CATEGORIA;


CREATE TABLE CATEGORIA (
   ID_CATEGORIA SERIAL PRIMARY KEY,
   NOME_CAT VARCHAR(50) NOT NULL,
   DESCRICAO_CAT VARCHAR(100)
);


CREATE TABLE AREA (
   ID_AREA SERIAL PRIMARY KEY,
   ID_CATEGORIA INT NOT NULL,
   NOME_AREA VARCHAR(50) NOT NULL,
   DESCRICAO_AR VARCHAR(100),
   CONSTRAINT FK_AREA_ADQUIRE_CATEGORI FOREIGN KEY (ID_CATEGORIA)
      REFERENCES CATEGORIA (ID_CATEGORIA)
);


CREATE TABLE TOPICO (
   ID_TOPICO SERIAL PRIMARY KEY,
   ID_AREA INT NOT NULL,
   NOME_TOPICO VARCHAR(50) NOT NULL,
   DESCRICAO_TOP VARCHAR(100) NOT NULL,
   CONSTRAINT FK_TOPICO_CONTAM_AREA FOREIGN KEY (ID_AREA)
      REFERENCES AREA (ID_AREA)
);


CREATE TABLE UTILIZADOR (
   ID_UTILIZADOR INT PRIMARY KEY,
   NOME_UTILIZADOR VARCHAR(1024) NOT NULL,
   PASSWORD_UTIL VARCHAR(16) NOT NULL,
   DATA_CRIACAO_UTILIZ TIMESTAMP NOT NULL,
   TELEMOVEL INT,
   GENERO INT NOT NULL,
   MORADA VARCHAR(100) NOT NULL,
   PAIS VARCHAR(100) NOT NULL,
   DATA_NASC TIMESTAMP NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   DATA_ATIV_UTILI TIMESTAMP,
   AUTEN2FAT BOOLEAN
);


CREATE TABLE S_S_O (
   ID_SSO SERIAL PRIMARY KEY,
   ID_UTILIZADOR INT NOT NULL,
   EMAIL_SSO VARCHAR(50) NOT NULL,
   TOKEN VARCHAR(2048) NOT NULL,
   CONSTRAINT FK_S_S_O_PODE_POSS_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR)
);


CREATE TABLE TWOFA (
   ID_2FA SERIAL PRIMARY KEY,
   ID_UTILIZADOR INT NOT NULL,
   CODIGO VARCHAR(6) NOT NULL,
   DATA_FA TIMESTAMP NOT NULL,
   CONSTRAINT FK_2FA_IRA_FAZER_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR)
);


CREATE TABLE GESTOR_ADMINISTRADOR (
   ID_UTILIZADOR INT NOT NULL,
   ID_GESTOR_ADMINISTRADOR SERIAL PRIMARY KEY,
   NOME_UTILIZADOR VARCHAR(1024) NOT NULL,
   PASSWORD_UTIL VARCHAR(16) NOT NULL,
   DATA_CRIACAO_UTILIZ TIMESTAMP NOT NULL,
   TELEMOVEL INT,
   GENERO INT NOT NULL,
   MORADA VARCHAR(100) NOT NULL,
   PAIS VARCHAR(100) NOT NULL,
   DATA_NASC TIMESTAMP NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   DATA_ATIV_UTILI TIMESTAMP,
   AUTEN2FAT BOOLEAN,
   CONSTRAINT FK_GESTOR_A_PODE_SER2_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR)
);


CREATE TABLE CURSOS (
   ID_CURSO SERIAL PRIMARY KEY,
   ID_TOPICO INT NOT NULL,
   ID_GESTOR_ADMINISTRADOR INT NOT NULL,
   ID_CATEGORIA INT NOT NULL,
   ID_AREA INT NOT NULL,
   NOME_CURSO VARCHAR(30) NOT NULL,
   DESCRICAO_CURSO VARCHAR(30) NOT NULL,
   NUMERO_VAGAS INT,
   DATA_INICIO_CURSO TIMESTAMP NOT NULL,
   DATA_FIM_CURSO TIMESTAMP NOT NULL,
   TIPO_CURSO INT NOT NULL,
   ESTADO INT NOT NULL,
   IDIOMA VARCHAR(50) NOT NULL,
   HORAS_CURSO FLOAT NOT NULL,
   CONTADOR_FORMANDOS INT NOT NULL,
   IMAGEM VARCHAR(200),
   CONSTRAINT FK_CURSOS_TEM_CATEGORI FOREIGN KEY (ID_CATEGORIA)
      REFERENCES CATEGORIA (ID_CATEGORIA),
   CONSTRAINT FK_CURSOS_POSSUI_AREA FOREIGN KEY (ID_AREA)
      REFERENCES AREA (ID_AREA),
   CONSTRAINT FK_CURSOS_CONTA_TOPICO FOREIGN KEY (ID_TOPICO)
      REFERENCES TOPICO (ID_TOPICO),
   CONSTRAINT FK_CURSOS_CRIA_GESTOR_A FOREIGN KEY (ID_GESTOR_ADMINISTRADOR)
      REFERENCES GESTOR_ADMINISTRADOR (ID_GESTOR_ADMINISTRADOR)
);


CREATE TABLE ASSINCRONO (
   ID_CURSO_ASSINCRONO SERIAL PRIMARY KEY,
   ID_CURSO INT NOT NULL,
   ID_TOPICO INT NOT NULL,
   ID_GESTOR_ADMINISTRADOR INT NOT NULL,
   ID_CATEGORIA INT NOT NULL,
   ID_AREA INT NOT NULL,
   NOME_CURSO VARCHAR(30) NOT NULL,
   DESCRICAO_CURSO VARCHAR(30) NOT NULL,
   NUMERO_VAGAS INT,
   DATA_INICIO_CURSO TIMESTAMP NOT NULL,
   DATA_FIM_CURSO TIMESTAMP NOT NULL,
   TIPO_CURSO INT NOT NULL,
   ESTADO INT NOT NULL,
   IDIOMA VARCHAR(50) NOT NULL,
   HORAS_CURSO FLOAT NOT NULL,
   CONTADOR_FORMANDOS INT NOT NULL,
   IMAGEM VARCHAR(200),
   CONSTRAINT FK_ASSINCRO_PODEM_SER_CURSOS FOREIGN KEY (ID_CURSO)
      REFERENCES CURSOS (ID_CURSO)
);


CREATE TABLE AULAS (
   ID_AULA SERIAL PRIMARY KEY,
   ID_CURSO INT NOT NULL,
   DATA_AULA TIMESTAMP NOT NULL,
   NOME_AULA VARCHAR(50) NOT NULL,
   CONSTRAINT FK_AULAS_E_CONSTIT_CURSOS FOREIGN KEY (ID_CURSO)
      REFERENCES CURSOS (ID_CURSO)
);


CREATE TABLE CONTEUDOS_PARTILHADO (
   ID_AREA_CONHECIMENTO SERIAL PRIMARY KEY,
   ID_AREA INT NOT NULL,
   ID_TOPICO INT NOT NULL,
   ID_CATEGORIA INT NOT NULL,
   DESCRICAO_CP VARCHAR(50),
   DATA_CRIACAO_CP TIMESTAMP NOT NULL,
   CONSTRAINT FK_CONTEUDO_DETEM_TOPICO FOREIGN KEY (ID_TOPICO)
      REFERENCES TOPICO (ID_TOPICO),
   CONSTRAINT FK_CONTEUDO_INCLUI_AREA FOREIGN KEY (ID_AREA)
      REFERENCES AREA (ID_AREA),
   CONSTRAINT FK_CONTEUDO_CONTEM_CATEGORI FOREIGN KEY (ID_CATEGORIA)
      REFERENCES CATEGORIA (ID_CATEGORIA)
);


CREATE TABLE POST (
   ID_POST SERIAL PRIMARY KEY,
   ID_UTILIZADOR INT NOT NULL,
   ID_AREA_CONHECIMENTO INT NOT NULL,
   TEXTO_POST VARCHAR(100) NOT NULL,
   CONTADOR_LIKES_POST INT NOT NULL,
   CONTADOR_COMENTARIOS INT NOT NULL,
   CONSTRAINT FK_POST_VAI_TER_CONTEUDO FOREIGN KEY (ID_AREA_CONHECIMENTO)
      REFERENCES CONTEUDOS_PARTILHADO (ID_AREA_CONHECIMENTO),
   CONSTRAINT FK_POST_ESCREVE_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR)
);


CREATE TABLE NOTIFICACOES_POST (
   ID_NOTIFICACAO_POST SERIAL PRIMARY KEY,
   ID_CURSO INT NOT NULL,
   ID_POST INT NOT NULL,
   ID_UTILIZADOR INT NOT NULL,
   DATA_HORA_NOTIFICACAOCP TIMESTAMP NOT NULL,
   CONSTRAINT FK_NOTIFICA_ENGLOBA_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR),
   CONSTRAINT FK_NOTIFICA_PODE_TER_CURSOS FOREIGN KEY (ID_CURSO)
      REFERENCES CURSOS (ID_CURSO),
   CONSTRAINT FK_NOTIFICA_PERTENEC_POST FOREIGN KEY (ID_POST)
      REFERENCES POST (ID_POST)
);


CREATE TABLE AVALIACOES (
   ID_AVALIACAO SERIAL PRIMARY KEY,
   ID_POST INT NOT NULL,
   ID_UTILIZADOR INT NOT NULL,
   AVALIACAO BOOLEAN NOT NULL,
   CONSTRAINT FK_AVALIACO_FAZER_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR),
   CONSTRAINT FK_AVALIACO_EXISTEM___POST FOREIGN KEY (ID_POST)
      REFERENCES POST (ID_POST)
);


CREATE TABLE COMENTARIO (
   ID_COMENTARIO SERIAL PRIMARY KEY,
   ID_POST INT NOT NULL,
   ID_UTILIZADOR INT NOT NULL,
   ID_AVALIACAO INT NOT NULL,
   TEXTO_COMENTARIO VARCHAR(500) NOT NULL,
   CONTADOR_LIKES_COM INT NOT NULL,
   CONSTRAINT FK_COMENTAR_RELATIONS_POST FOREIGN KEY (ID_POST)
      REFERENCES POST (ID_POST),
   CONSTRAINT FK_COMENTAR_ESCREVE__UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR),
   CONSTRAINT FK_COMENTAR_EXISTEM__AVALIACO FOREIGN KEY (ID_AVALIACAO)
      REFERENCES AVALIACOES (ID_AVALIACAO)
);


CREATE TABLE TIPO_FORMATO (
   ID_FORMATO SERIAL PRIMARY KEY,
   FORMATO VARCHAR(200) NOT NULL
);


CREATE TABLE CONTEUDOS (
   ID_CONTEUDO SERIAL PRIMARY KEY,
   ID_AULA INT NOT NULL,
   ID_FORMATO INT NOT NULL,
   CONTEUDO VARCHAR(200) NOT NULL,
   CONSTRAINT FK_CONTEUDO_TEM_DISPO_AULAS FOREIGN KEY (ID_AULA)
      REFERENCES AULAS (ID_AULA),
   CONSTRAINT FK_CONTEUDO_REUNE_TIPO_FOR FOREIGN KEY (ID_FORMATO)
      REFERENCES TIPO_FORMATO (ID_FORMATO)
);


CREATE TABLE TIPO_DENUNCIA (
   ID_TIPO_DENUNCIA SERIAL PRIMARY KEY,
   TIPO_DENUNCIA VARCHAR(100) NOT NULL
);


CREATE TABLE DENUNCIA (
   ID_DENUNCIA SERIAL PRIMARY KEY,
   ID_COMENTARIO INT NOT NULL,
   ID_UTILIZADOR INT NOT NULL,
   ID_POST INT NOT NULL,
   ID_TIPO_DENUNCIA INT NOT NULL,
   CONSTRAINT FK_DENUNCIA_REALIZA_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR),
   CONSTRAINT FK_DENUNCIA_POSSUIR_TIPO_DEN FOREIGN KEY (ID_TIPO_DENUNCIA)
      REFERENCES TIPO_DENUNCIA (ID_TIPO_DENUNCIA),
   CONSTRAINT FK_DENUNCIA_RELATIONS_POST FOREIGN KEY (ID_POST)
      REFERENCES POST (ID_POST),
   CONSTRAINT FK_DENUNCIA_PERTENCE_COMENTAR FOREIGN KEY (ID_COMENTARIO)
      REFERENCES COMENTARIO (ID_COMENTARIO)
);


CREATE TABLE FORMADORES (
   ID_FORMADOR SERIAL PRIMARY KEY,
   ID_UTILIZADOR INT NOT NULL,
   NOME_UTILIZADOR VARCHAR(1024) NOT NULL,
   PASSWORD_UTIL VARCHAR(16) NOT NULL,
   DATA_CRIACAO_UTILIZ TIMESTAMP NOT NULL,
   TELEMOVEL INT NULL,
   GENERO INT NOT NULL,
   MORADA VARCHAR(100) NOT NULL,
   PAIS VARCHAR(100) NOT NULL,
   DATA_NASC TIMESTAMP NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   DATA_ATIV_UTILI TIMESTAMP NULL,
   AUTEN2FAT BOOLEAN NULL,
   ESPECIALIDADES VARCHAR(100) NULL,
   EXPERIENCIA VARCHAR(100) NULL,
   CONSTRAINT FK_FORMADOR_PODE_SER3_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR)
);


CREATE TABLE FORMANDOS (
   ID_FORMANDO SERIAL PRIMARY KEY,
   ID_UTILIZADOR INT NOT NULL,
   NOME_UTILIZADOR VARCHAR(1024) NOT NULL,
   PASSWORD_UTIL VARCHAR(16) NOT NULL,
   DATA_CRIACAO_UTILIZ TIMESTAMP NOT NULL,
   TELEMOVEL INT NULL,
   GENERO INT NOT NULL,
   MORADA TEXT NOT NULL,
   PAIS TEXT NOT NULL,
   DATA_NASC TIMESTAMP NOT NULL,
   EMAIL VARCHAR(50) NOT NULL,
   DATA_ATIV_UTILI TIMESTAMP NULL,
   AUTEN2FAT BOOLEAN NULL,
   PERCURSO_FORMATIVO VARCHAR(100) NULL,
   CONSTRAINT FK_FORMANDO_PODE_SER_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR)
);


CREATE TABLE INSCRICOES (
   ID_INSCRICAO SERIAL PRIMARY KEY,
   ID_FORMANDO INT NOT NULL,
   ID_CURSO INT NOT NULL,
   DATA_LIMITE TIMESTAMP NOT NULL,
   DATA_INICIO_INSC TIMESTAMP NOT NULL,
   STATUS_INSCRICAO INT NOT NULL,
   CONSTRAINT FK_INSCRICO_DETERMINA_CURSOS FOREIGN KEY (ID_CURSO)
      REFERENCES CURSOS (ID_CURSO),
   CONSTRAINT FK_INSCRICO_REALIZAM_FORMANDO FOREIGN KEY (ID_FORMANDO)
      REFERENCES FORMANDOS (ID_FORMANDO)
);


CREATE TABLE NOTIFICACOES_CURSO (
   ID_NOTIFICACAO_CURSOS SERIAL PRIMARY KEY,
   ID_UTILIZADOR INT NOT NULL,
   ID_CURSO INT NOT NULL,
   DATA_HORA_NOTIFICACAOCURSO TIMESTAMP NOT NULL,
   CONSTRAINT FK_NOTIFICA_VAI_RECEB_UTILIZAD FOREIGN KEY (ID_UTILIZADOR)
      REFERENCES UTILIZADOR (ID_UTILIZADOR),
   CONSTRAINT FK_NOTIFICA_TERA_CURSOS FOREIGN KEY (ID_CURSO)
      REFERENCES CURSOS (ID_CURSO)
);


CREATE TABLE OCORRENCIAS_EDICOES (
   NR_OCORRENCIA INT NOT NULL PRIMARY KEY,
   ID_CURSO INT NOT NULL,
   CONSTRAINT FK_OCORRENC_CONTEM_VA_CURSOS FOREIGN KEY (ID_CURSO)
      REFERENCES CURSOS (ID_CURSO)
);


CREATE TABLE SINCRONO (
   ID_CURSO_SINCRONO SERIAL PRIMARY KEY,
   ID_CURSO INT NOT NULL,
   ID_FORMADOR INT NOT NULL,
   ID_TOPICO INT NOT NULL,
   ID_GESTOR_ADMINISTRADOR INT NOT NULL,
   ID_CATEGORIA INT NOT NULL,
   ID_AREA INT NOT NULL,
   NOME_CURSO VARCHAR(30) NOT NULL,
   DESCRICAO_CURSO VARCHAR(30) NOT NULL,
   NUMERO_VAGAS INT NULL,
   DATA_INICIO_CURSO TIMESTAMP NOT NULL,
   DATA_FIM_CURSO TIMESTAMP NOT NULL,
   TIPO_CURSO INT NOT NULL,
   ESTADO INT NOT NULL,
   IDIOMA TEXT NOT NULL,
   HORAS_CURSO FLOAT NOT NULL,
   CONTADOR_FORMANDOS INT NOT NULL,
   IMAGEM VARCHAR(200) NULL,
   N_MAX_FORM INT NOT NULL,
   CONSTRAINT FK_SINCRONO_LECIONAM_FORMADOR FOREIGN KEY (ID_FORMADOR)
      REFERENCES FORMADORES (ID_FORMADOR),
   CONSTRAINT FK_SINCRONO_PODEM_SER_CURSOS FOREIGN KEY (ID_CURSO)
      REFERENCES CURSOS (ID_CURSO)
);


CREATE TABLE RESULTADOS (
   ID_RESUL SERIAL PRIMARY KEY,
   ID_FORMANDO INT NOT NULL,
   ID_CURSO_SINCRONO INT NOT NULL,
   RESUL FLOAT NOT NULL,
   CONSTRAINT FK_RESULTAD_VAI_POSSU_SINCRONO FOREIGN KEY (ID_CURSO_SINCRONO)
      REFERENCES SINCRONO (ID_CURSO_SINCRONO),
   CONSTRAINT FK_RESULTAD_CLASSIFIC_FORMANDO FOREIGN KEY (ID_FORMANDO)
      REFERENCES FORMANDOS (ID_FORMANDO)
);
