// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxToQib9JZHIm6IAkyo0wBPXjlpO1Ka-Y',
    appId: '1:695425925082:web:2190332938fbec357f0ae3',
    messagingSenderId: '695425925082',
    projectId: 'pint-5f0b7',
    authDomain: 'pint-5f0b7.firebaseapp.com',
    storageBucket: 'pint-5f0b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlo6PDAIFxqp0TyvlXyCGBnEcDJJ4BLxk',
    appId: '1:695425925082:android:80710fb02e396dd47f0ae3',
    messagingSenderId: '695425925082',
    projectId: 'pint-5f0b7',
    storageBucket: 'pint-5f0b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsz4wfuDW9BiCA5LH61Rl_D6-i5b4pCuc',
    appId: '1:695425925082:ios:ed7dbf5f74a59c977f0ae3',
    messagingSenderId: '695425925082',
    projectId: 'pint-5f0b7',
    storageBucket: 'pint-5f0b7.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsz4wfuDW9BiCA5LH61Rl_D6-i5b4pCuc',
    appId: '1:695425925082:ios:ed7dbf5f74a59c977f0ae3',
    messagingSenderId: '695425925082',
    projectId: 'pint-5f0b7',
    storageBucket: 'pint-5f0b7.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxToQib9JZHIm6IAkyo0wBPXjlpO1Ka-Y',
    appId: '1:695425925082:web:517ec2fb0112de257f0ae3',
    messagingSenderId: '695425925082',
    projectId: 'pint-5f0b7',
    authDomain: 'pint-5f0b7.firebaseapp.com',
    storageBucket: 'pint-5f0b7.firebasestorage.app',
  );
}
