// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLR_SI3xSW-tWa4wxRnKRShGSNIA2-EQ',
    appId: '1:72896881333:web:e8c2cd14b93f7018a114fc',
    messagingSenderId: '72896881333',
    projectId: 'softskills-f3ab6',
    authDomain: 'softskills-f3ab6.firebaseapp.com',
    storageBucket: 'softskills-f3ab6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC85FaoEQArK9sghjL3aAreRocgHuDEcLQ',
    appId: '1:72896881333:android:2b205a0c00a5b1c2a114fc',
    messagingSenderId: '72896881333',
    projectId: 'softskills-f3ab6',
    storageBucket: 'softskills-f3ab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFOjNHnleRr1orF4-9mH_WjJ6pDehpuY8',
    appId: '1:72896881333:ios:26463728ed04b3d4a114fc',
    messagingSenderId: '72896881333',
    projectId: 'softskills-f3ab6',
    storageBucket: 'softskills-f3ab6.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFOjNHnleRr1orF4-9mH_WjJ6pDehpuY8',
    appId: '1:72896881333:ios:26463728ed04b3d4a114fc',
    messagingSenderId: '72896881333',
    projectId: 'softskills-f3ab6',
    storageBucket: 'softskills-f3ab6.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoLR_SI3xSW-tWa4wxRnKRShGSNIA2-EQ',
    appId: '1:72896881333:web:a85111dce2e8e8d4a114fc',
    messagingSenderId: '72896881333',
    projectId: 'softskills-f3ab6',
    authDomain: 'softskills-f3ab6.firebaseapp.com',
    storageBucket: 'softskills-f3ab6.firebasestorage.app',
  );
}
