-- CATEGORIA
SELECT * FROM CATEGORIA;

-- AREA
SELECT * FROM AREA;

-- TOPICO
SELECT * FROM TOPICO;

-- UTILIZADOR
SELECT * FROM UTILIZADOR;

-- S_S_O
SELECT * FROM S_S_O;

-- TWOFA
SELECT * FROM TWOFA;

-- GESTOR_ADMINISTRADOR
SELECT * FROM GESTOR_ADMINISTRADOR;

-- CURSOS
SELECT * FROM CURSOS;

-- ASSINCRONO
SELECT * FROM ASSINCRONO;

-- AULAS
SELECT * FROM AULAS;

-- CONTEUDOS_PARTILHADO
SELECT * FROM CONTEUDOS_PARTILHADO;

-- POST
SELECT * FROM POST;

-- COMENTARIO
SELECT * FROM COMENTARIO;

-- NOTIFICACOES_COMENTARIOS_POST
SELECT * FROM NOTIFICACOES_COMENTARIOS_POST;

-- TIPO_FORMATO
SELECT * FROM TIPO_FORMATO;

-- MATERIAL_APOIO
SELECT * FROM MATERIAL_APOIO;

-- CONTEUDOS
SELECT * FROM CONTEUDOS;

-- TIPO_DENUNCIA
SELECT * FROM TIPO_DENUNCIA;

-- DENUNCIA
SELECT * FROM DENUNCIA;

-- FORMADORES
SELECT * FROM FORMADORES;

-- FORMANDOS
SELECT * FROM FORMANDOS;

-- FAVORITOS
SELECT * FROM FAVORITOS;

-- INSCRICOES
SELECT * FROM INSCRICOES;

-- NOTIFICACOES_CURSO
SELECT * FROM NOTIFICACOES_CURSO;

-- OCORRENCIAS_EDICOES
SELECT * FROM OCORRENCIAS_EDICOES;

-- SINCRONO
SELECT * FROM SINCRONO;

-- RESULTADOS
SELECT * FROM RESULTADOS;

-- CONTEUDOS_FORUM
SELECT * FROM CONTEUDOS_FORUM;

-- MODELO_CERTIFICADO
SELECT * FROM MODELO_CERTIFICADO;

-- CERTIFICADOS
SELECT * FROM CERTIFICADOS;